In [1]:
import numpy as np
import pandas as pd
from sklearn.naive_bayes import GaussianNB
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import confusion_matrix,r2_score,classification_report

In [2]:
df = pd.read_csv('adult.csv')
df

39          State-gov   77516    Bachelors   13        Never-married  \
0      50   Self-emp-not-inc   83311    Bachelors   13   Married-civ-spouse   
1      38            Private  215646      HS-grad    9             Divorced   
2      53            Private  234721         11th    7   Married-civ-spouse   
3      28            Private  338409    Bachelors   13   Married-civ-spouse   
4      37            Private  284582      Masters   14   Married-civ-spouse   
...    ..                ...     ...          ...  ...                  ...   
32555  27            Private  257302   Assoc-acdm   12   Married-civ-spouse   
32556  40            Private  154374      HS-grad    9   Married-civ-spouse   
32557  58            Private  151910      HS-grad    9              Widowed   
32558  22            Private  201490      HS-grad    9        Never-married   
32559  52       Self-emp-inc  287927      HS-grad    9   Married-civ-spouse   

             Adm-clerical   Not-in-family   White     Male   2174   0   40  \
0         Exec-managerial         Husband   White     Male      0   0   13   
1       Handlers-cleaners   Not-in-family   White     Male      0   0   40   
2       Handlers-cleaners         Husband   Black     Male      0   0   40   
3          Prof-specialty            Wife   Black   Female      0   0   40   
4         Exec-managerial            Wife   White   Female      0   0   40   
...                   ...             ...     ...      ...    ...  ..  ...   
32555        Tech-support            Wife   White   Female      0   0   38   
32556   Machine-op-inspct         Husband   White     Male      0   0   40   
32557        Adm-clerical       Unmarried   White   Female      0   0   40   
32558        Adm-clerical       Own-child   White     Male      0   0   20   
32559     Exec-managerial            Wife   White   Female  15024   0   40   

        United-States   <=50K  
0       United-States   <=50K  
1       United-States   <=50K  
2       United-States   <=50K  
3                Cuba   <=50K  
4       United-States   <=50K  
...               ...     ...  
32555   United-States   <=50K  
32556   United-States    >50K  
32557   United-States   <=50K  
32558   United-States   <=50K  
32559   United-States    >50K  

[32560 rows x 15 columns]

In [3]:
df.columns = ['Age', 'Workclass', 'Fnlwgt', 'Education', 'education_num', 'marital_status',
 'occupation', 'relationship', 'race', 'sex', 'capital_gain', 'capital_loss',
 'hours_per_week', 'native_country', 'income']
df

Age          Workclass  Fnlwgt    Education  education_num  \
0       50   Self-emp-not-inc   83311    Bachelors             13   
1       38            Private  215646      HS-grad              9   
2       53            Private  234721         11th              7   
3       28            Private  338409    Bachelors             13   
4       37            Private  284582      Masters             14   
...    ...                ...     ...          ...            ...   
32555   27            Private  257302   Assoc-acdm             12   
32556   40            Private  154374      HS-grad              9   
32557   58            Private  151910      HS-grad              9   
32558   22            Private  201490      HS-grad              9   
32559   52       Self-emp-inc  287927      HS-grad              9   

            marital_status          occupation    relationship    race  \
0       Married-civ-spouse     Exec-managerial         Husband   White   
1                 Divorced   Handlers-cleaners   Not-in-family   White   
2       Married-civ-spouse   Handlers-cleaners         Husband   Black   
3       Married-civ-spouse      Prof-specialty            Wife   Black   
4       Married-civ-spouse     Exec-managerial            Wife   White   
...                    ...                 ...             ...     ...   
32555   Married-civ-spouse        Tech-support            Wife   White   
32556   Married-civ-spouse   Machine-op-inspct         Husband   White   
32557              Widowed        Adm-clerical       Unmarried   White   
32558        Never-married        Adm-clerical       Own-child   White   
32559   Married-civ-spouse     Exec-managerial            Wife   White   

           sex  capital_gain  capital_loss  hours_per_week  native_country  \
0         Male             0             0              13   United-States   
1         Male             0             0              40   United-States   
2         Male             0             0              40   United-States   
3       Female             0             0              40            Cuba   
4       Female             0             0              40   United-States   
...        ...           ...           ...             ...             ...   
32555   Female             0             0              38   United-States   
32556     Male             0             0              40   United-States   
32557   Female             0             0              40   United-States   
32558     Male             0             0              20   United-States   
32559   Female         15024             0              40   United-States   

       income  
0       <=50K  
1       <=50K  
2       <=50K  
3       <=50K  
4       <=50K  
...       ...  
32555   <=50K  
32556    >50K  
32557   <=50K  
32558   <=50K  
32559    >50K  

[32560 rows x 15 columns]

In [4]:
df.isnull().sum()

Age               0
Workclass         0
Fnlwgt            0
Education         0
education_num     0
marital_status    0
occupation        0
relationship      0
race              0
sex               0
capital_gain      0
capital_loss      0
hours_per_week    0
native_country    0
income            0
dtype: int64

In [5]:
df.shape

(32560, 15)

In [6]:
df.dtypes

Age                int64
Workclass         object
Fnlwgt             int64
Education         object
education_num      int64
marital_status    object
occupation        object
relationship      object
race              object
sex               object
capital_gain       int64
capital_loss       int64
hours_per_week     int64
native_country    object
income            object
dtype: object

In [7]:
print(df['Workclass'].value_counts())
print(df['Education'].value_counts())
print(df['marital_status'].value_counts())
print(df['occupation'].value_counts())
print(df['relationship'].value_counts())
print(df['race'].value_counts())
print(df['sex'].value_counts())
print(df['native_country'].value_counts())
print(df['income'].value_counts())

 Private             22696
 Self-emp-not-inc     2541
 Local-gov            2093
 ?                    1836
 State-gov            1297
 Self-emp-inc         1116
 Federal-gov           960
 Without-pay            14
 Never-worked            7
Name: Workclass, dtype: int64
 HS-grad         10501
 Some-college     7291
 Bachelors        5354
 Masters          1723
 Assoc-voc        1382
 11th             1175
 Assoc-acdm       1067
 10th              933
 7th-8th           646
 Prof-school       576
 9th               514
 12th              433
 Doctorate         413
 5th-6th           333
 1st-4th           168
 Preschool          51
Name: Education, dtype: int64
 Married-civ-spouse       14976
 Never-married            10682
 Divorced                  4443
 Separated                 1025
 Widowed                    993
 Married-spouse-absent      418
 Married-AF-spouse           23
Name: marital_status, dtype: int64
 Prof-specialty       4140
 Craft-repair         4099
 Exec-managerial

In [8]:
#df = df[str(df['Workclass']) == '?']
df.drop(df.loc[df['Workclass'] == ' ?'].index,inplace=True,axis=0)
df.drop(df.loc[df['occupation'] ==' ?'].index,inplace=True,axis=0)
df.drop(df.loc[df['native_country'] == ' ?'].index,inplace=True,axis=0)

In [9]:
print(df['Workclass'].value_counts())
print(df['Education'].value_counts())
print(df['marital_status'].value_counts())
print(df['occupation'].value_counts())
print(df['relationship'].value_counts())
print(df['race'].value_counts())
print(df['sex'].value_counts())
print(df['native_country'].value_counts())
print(df['income'].value_counts())

 Private             22286
 Self-emp-not-inc     2499
 Local-gov            2067
 State-gov            1278
 Self-emp-inc         1074
 Federal-gov           943
 Without-pay            14
Name: Workclass, dtype: int64
 HS-grad         9840
 Some-college    6678
 Bachelors       5043
 Masters         1627
 Assoc-voc       1307
 11th            1048
 Assoc-acdm      1008
 10th             820
 7th-8th          557
 Prof-school      542
 9th              455
 12th             377
 Doctorate        375
 5th-6th          288
 1st-4th          151
 Preschool         45
Name: Education, dtype: int64
 Married-civ-spouse       14065
 Never-married             9725
 Divorced                  4214
 Separated                  939
 Widowed                    827
 Married-spouse-absent      370
 Married-AF-spouse           21
Name: marital_status, dtype: int64
 Prof-specialty       4038
 Craft-repair         4030
 Exec-managerial      3992
 Adm-clerical         3720
 Sales                3584
 Othe

In [10]:
df['Workclass'].unique()

array([' Self-emp-not-inc', ' Private', ' State-gov', ' Federal-gov',
       ' Local-gov', ' Self-emp-inc', ' Without-pay'], dtype=object)

In [11]:
from sklearn.preprocessing import LabelEncoder
lb = LabelEncoder()

In [12]:
df['Workclass'] = lb.fit_transform(df['Workclass'])
df['Education'] = lb.fit_transform(df['Education'])
df['marital_status'] = lb.fit_transform(df['marital_status'])
df['occupation'] = lb.fit_transform(df['occupation'])
df['relationship'] = lb.fit_transform(df['relationship'])
df['race'] = lb.fit_transform(df['race'])
df['sex'] = lb.fit_transform(df['sex'])
df['native_country'] = lb.fit_transform(df['native_country'])
df['income'] = lb.fit_transform(df['income'])

In [13]:
df.dtypes

Age               int64
Workclass         int32
Fnlwgt            int64
Education         int32
education_num     int64
marital_status    int32
occupation        int32
relationship      int32
race              int32
sex               int32
capital_gain      int64
capital_loss      int64
hours_per_week    int64
native_country    int32
income            int32
dtype: object

In [14]:
df.head()

Age  Workclass  Fnlwgt  Education  education_num  marital_status  \
0   50          4   83311          9             13               2   
1   38          2  215646         11              9               0   
2   53          2  234721          1              7               2   
3   28          2  338409          9             13               2   
4   37          2  284582         12             14               2   

   occupation  relationship  race  sex  capital_gain  capital_loss  \
0           3             0     4    1             0             0   
1           5             1     4    1             0             0   
2           5             0     2    1             0             0   
3           9             5     2    0             0             0   
4           3             5     4    0             0             0   

   hours_per_week  native_country  income  
0              13              38       0  
1              40              38       0  
2              40              38       0  
3              40               4       0  
4              40              38       0

In [15]:
print(df['Workclass'].value_counts())
print(df['Education'].value_counts())
print(df['marital_status'].value_counts())
print(df['occupation'].value_counts())
print(df['relationship'].value_counts())
print(df['race'].value_counts())
print(df['sex'].value_counts())
print(df['native_country'].value_counts())
print(df['income'].value_counts())

2    22286
4     2499
1     2067
5     1278
3     1074
0      943
6       14
Name: Workclass, dtype: int64
11    9840
15    6678
9     5043
12    1627
8     1307
1     1048
7     1008
0      820
5      557
14     542
6      455
2      377
10     375
4      288
3      151
13      45
Name: Education, dtype: int64
2    14065
4     9725
0     4214
5      939
6      827
3      370
1       21
Name: marital_status, dtype: int64
9     4038
2     4030
3     3992
0     3720
11    3584
7     3212
6     1966
13    1572
5     1350
4      989
12     912
10     644
8      143
1        9
Name: occupation, dtype: int64
0    12463
1     7725
3     4466
4     3212
5     1406
2      889
Name: relationship, dtype: int64
4    25932
2     2817
1      895
0      286
3      231
Name: race, dtype: int64
1    20379
0     9782
Name: sex, dtype: int64
38    27503
25      610
29      188
10      128
32      109
1       107
7       100
18      100
4        92
8        86
22       80
34       71
2        68
21       

### SO LABEL ENCODING MAKES
<=50K  == 0<br>50K  == 1

In [16]:
# function to implement different models use later
def apply_model(model,x_train,y_train,x_test,y_test):
    m=model
    m.fit(x_train,y_train)
    print("TRAINING SCORE: ", m.score(x_train,y_train),'\n')
    print('TEST SCORE: ', m.score(x_test,y_test),'\n')
    y_pred = m.predict(x_test)
    print('YPRED\n', y_pred,'\n')
    cm = confusion_matrix(y_test,y_pred)
    print('CONFUSION MATRIX: \n', cm,'\n')
    print("CLASSIFICATION REPORT: \n", classification_report(y_test,y_pred))

In [17]:
from sklearn.model_selection import train_test_split

In [18]:
x = df.iloc[:,0:-1]
y = df.iloc[:,-1]
print(x.shape)
print(y.shape)

(30161, 14)
(30161,)


In [19]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.25,random_state=0)
print(x_train.shape,y_train.shape,x_test.shape,y_test.shape)

(22620, 14) (22620,) (7541, 14) (7541,)


In [20]:
gnb = GaussianNB()
lg = LogisticRegression(solver='liblinear')
dt = DecisionTreeClassifier(criterion='entropy')
knn = KNeighborsClassifier(n_neighbors=10)
rf = RandomForestClassifier(n_estimators=70,criterion='gini',max_depth=7)

In [21]:
# APPLYING LINEAR REGRESSION MODEL
apply_model(lg,x_train,y_train,x_test,y_test)

TRAINING SCORE:  0.7930150309460654 

TEST SCORE:  0.7935287097201963 

YPRED
 [0 0 0 ... 0 0 0] 

CONFUSION MATRIX: 
 [[5491  240]
 [1317  493]] 

CLASSIFICATION REPORT: 
               precision    recall  f1-score   support

           0       0.81      0.96      0.88      5731
           1       0.67      0.27      0.39      1810

    accuracy                           0.79      7541
   macro avg       0.74      0.62      0.63      7541
weighted avg       0.77      0.79      0.76      7541



In [22]:
# APPLYING DESICION TREE MODEL
apply_model(dt,x_train,y_train,x_test,y_test)

TRAINING SCORE:  0.9999557913351017 

TEST SCORE:  0.8029439066436812 

YPRED
 [0 0 1 ... 0 1 0] 

CONFUSION MATRIX: 
 [[4971  760]
 [ 726 1084]] 

CLASSIFICATION REPORT: 
               precision    recall  f1-score   support

           0       0.87      0.87      0.87      5731
           1       0.59      0.60      0.59      1810

    accuracy                           0.80      7541
   macro avg       0.73      0.73      0.73      7541
weighted avg       0.80      0.80      0.80      7541



In [23]:
# APPLYING KNN MODEL
apply_model(knn,x_train,y_train,x_test,y_test)

TRAINING SCORE:  0.802077807250221 

TEST SCORE:  0.7919374088317199 

YPRED
 [0 0 0 ... 0 0 0] 

CONFUSION MATRIX: 
 [[5585  146]
 [1423  387]] 

CLASSIFICATION REPORT: 
               precision    recall  f1-score   support

           0       0.80      0.97      0.88      5731
           1       0.73      0.21      0.33      1810

    accuracy                           0.79      7541
   macro avg       0.76      0.59      0.60      7541
weighted avg       0.78      0.79      0.75      7541



In [24]:
# APPLYING RANDOM FOREST MODEL
apply_model(rf,x_train,y_train,x_test,y_test)

TRAINING SCORE:  0.8535366931918656 

TEST SCORE:  0.8504177164832251 

YPRED
 [0 0 0 ... 0 0 0] 

CONFUSION MATRIX: 
 [[5478  253]
 [ 875  935]] 

CLASSIFICATION REPORT: 
               precision    recall  f1-score   support

           0       0.86      0.96      0.91      5731
           1       0.79      0.52      0.62      1810

    accuracy                           0.85      7541
   macro avg       0.82      0.74      0.77      7541
weighted avg       0.84      0.85      0.84      7541



In [25]:
# APPLYING GAUSSIAN NAIVE BAYES MODEL
apply_model(gnb,x_train,y_train,x_test,y_test)

TRAINING SCORE:  0.7885941644562334 

TEST SCORE:  0.7866330725367988 

YPRED
 [0 0 0 ... 0 0 0] 

CONFUSION MATRIX: 
 [[5412  319]
 [1290  520]] 

CLASSIFICATION REPORT: 
               precision    recall  f1-score   support

           0       0.81      0.94      0.87      5731
           1       0.62      0.29      0.39      1810

    accuracy                           0.79      7541
   macro avg       0.71      0.62      0.63      7541
weighted avg       0.76      0.79      0.76      7541

